name: Test

on:
  push:
    branches:
      - main

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./cypress/
          platforms: linux/amd64
          push: true
          tags: fpsl/dummy-runners:cypress-${{ steps.short-sha.outputs.sha }}
      - run: docker run --rm fpsl/dummy-runners:cypress-${{ steps.short-sha.outputs.sha }}
      - uses: saucelabs/saucectl-run-action@v3
        env:
          DOCKER_IMAGE: fpsl/dummy-runners:cypress-${{ steps.short-sha.outputs.sha }}
        with:
          working-directory: ./cypress
      - run: tree ./cypress/artifacts

  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./playwright/
          platforms: linux/amd64
          push: true
          tags: fpsl/dummy-runners:playwright-${{ steps.short-sha.outputs.sha }}
      - run: docker run --rm fpsl/dummy-runners:playwright-${{ steps.short-sha.outputs.sha }}
      - uses: saucelabs/saucectl-run-action@v3
        env:
          DOCKER_IMAGE: fpsl/dummy-runners:playwright-${{ steps.short-sha.outputs.sha }}
        with:
          working-directory: ./playwright
      - run: tree ./playwright/artifacts

  testcafe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./testcafe/
          platforms: linux/amd64
          push: true
          tags: fpsl/dummy-runners:testcafe-${{ steps.short-sha.outputs.sha }}
      - uses: saucelabs/saucectl-run-action@v3
        env:
          DOCKER_IMAGE: fpsl/dummy-runners:testcafe-${{ steps.short-sha.outputs.sha }}
        with:
          working-directory: ./testcafe
      - run: tree ./testcafe/artifacts
